# Generated by Django 4.2.30 on 2026-06-16 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, default='', max_length=150, verbose_name='Nama Lengkap')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Nomor Telepon')),
                ('occupation', models.CharField(blank=True, default='', max_length=100, verbose_name='Pekerjaan')),
                ('home_address', models.TextField(blank=True, default='', verbose_name='Alamat Rumah')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Foto Profil')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Terverifikasi')),
                ('trust_score', models.PositiveIntegerField(default=85, verbose_name='Community Trust Score')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Judul Laporan')),
                ('category', models.CharField(choices=[('infrastructure', 'Infrastructure'), ('environment', 'Environment'), ('public_safety', 'Public Safety'), ('other', 'Other')], default='infrastructure', max_length=50, verbose_name='Kategori')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10, verbose_name='Prioritas')),
                ('description', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('location_address', models.CharField(blank=True, max_length=255, verbose_name='Alamat Lokasi')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('pending_publication', 'Pending Publication')], default='pending', max_length=30, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Submission',
                'verbose_name_plural': 'Submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
