# Generated by Django 4.2.30 on 2026-06-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_submission_latitude_submission_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.CharField(default='id', max_length=10, verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(default='Asia/Jakarta', max_length=50, verbose_name='Timezone'),
        ),
    ]
