# Generated by Django 4.2.30 on 2026-06-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userprofile_language_userprofile_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='notif_email',
            field=models.BooleanField(default=True, verbose_name='Notifikasi Email'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notif_push',
            field=models.BooleanField(default=True, verbose_name='Notifikasi Push'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notif_sms',
            field=models.BooleanField(default=False, verbose_name='Notifikasi SMS'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='privacy_mode',
            field=models.CharField(choices=[('transparent', 'Transparansi Penuh'), ('anonymous', 'Pelaporan Rahasia')], default='transparent', max_length=20, verbose_name='Mode Privasi'),
        ),
    ]
