# Generated by Django 4.2.30 on 2026-06-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userprofile_notif_email_userprofile_notif_push_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mfa_enabled',
            field=models.BooleanField(default=False, verbose_name='Autentikasi Dua Faktor'),
        ),
    ]
