# Generated by Django 6.0.3 on 2026-06-12 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, default='', max_length=150, verbose_name='Nama Lengkap')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Nomor Telepon')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Tanggal Lahir')),
                ('birth_place', models.CharField(blank=True, default='', max_length=100, verbose_name='Tempat Lahir')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Umur')),
                ('gender', models.CharField(blank=True, choices=[('', '-'), ('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], default='', max_length=20, verbose_name='Jenis Kelamin')),
                ('department', models.CharField(blank=True, default='', max_length=150, verbose_name='Departemen')),
                ('position', models.CharField(blank=True, default='', max_length=150, verbose_name='Jabatan')),
                ('supervisor', models.CharField(blank=True, default='', max_length=150, verbose_name='Supervisor')),
                ('duty_start', models.TimeField(blank=True, null=True, verbose_name='Jam Masuk')),
                ('duty_end', models.TimeField(blank=True, null=True, verbose_name='Jam Selesai')),
                ('memo_text', models.TextField(blank=True, default='', verbose_name='Internal Memo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Profile',
                'verbose_name_plural': 'Admin Profiles',
            },
        ),
    ]
