# Generated by Django 4.2.30 on 2026-06-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0002_blockedip'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(default='AduanCepat Institutional', max_length=255, verbose_name='Nama Organisasi')),
                ('domain', models.CharField(default='portal.aduancepat.gov', max_length=255, verbose_name='Domain Utama')),
                ('language', models.CharField(choices=[('en', 'English (US)'), ('id', 'Bahasa Indonesia')], default='id', max_length=50, verbose_name='Bahasa Sistem')),
                ('timezone', models.CharField(choices=[('Asia/Jakarta', 'UTC +7:00 (Jakarta)'), ('Asia/Makassar', 'UTC +8:00 (Makassar)')], default='Asia/Jakarta', max_length=50, verbose_name='Zona Waktu')),
                ('mod_auto', models.BooleanField(default=True, verbose_name='Moderasi Otomatis')),
                ('notif_email', models.BooleanField(default=True, verbose_name='Notifikasi Email')),
                ('public_analytic', models.BooleanField(default=False, verbose_name='Analitik Publik')),
                ('mfa_required', models.BooleanField(default=True, verbose_name='Autentikasi Multi-Faktor')),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
