# Generated by Django 4.2.30 on 2026-06-17 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('akun', '0003_sitesetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Alamat IP')),
                ('path', models.CharField(max_length=500, verbose_name='Halaman Diakses')),
                ('method', models.CharField(default='GET', max_length=10)),
                ('status', models.CharField(choices=[('allowed', 'Diizinkan'), ('blocked', 'Diblokir'), ('login_failed', 'Login Gagal'), ('login_success', 'Login Berhasil')], default='allowed', max_length=20)),
                ('user_agent', models.TextField(blank=True, verbose_name='Browser/Device')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Pengguna')),
            ],
            options={
                'verbose_name': 'Security Log',
                'verbose_name_plural': 'Security Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
